# Generated by Django 3.2.6 on 2024-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_postcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
